version: '3.8'

services:
  trading-journal:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
